-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local M = {}

M.color = "31FF2EFF"

M.inactive_color = "31FF2E51"

return M