-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local M = {}

M.color = "FF00E6FF"

M.inactive_color = "FF00E651"

return M