-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local M = {}

M.color = "FF0000FF"

M.inactive_color = "FF000051"

return M