-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local M = {}

M.color = "FFFF00FF"

M.inactive_color = "FFFF0051"

return M