-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    animations = {
        enabled = true,
    },
})
hl.curve("Bezier", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "Bezier" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 10, bezier = "Bezier", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 10, bezier = "Bezier", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 10, bezier = "Bezier", style = "slide" })
hl.animation({ leaf = "fade", enabled = true, speed = 10, bezier = "Bezier" })
hl.animation({ leaf = "layers", enabled = true, speed = 10, bezier = "Bezier", style = "fade" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 10, bezier = "Bezier", style = "slidevert" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 10, bezier = "Bezier" })
