-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    decoration = {
        rounding = 5,
        rounding_power = 10.0,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
    },
})
