-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local themes_current = require("themes.current")

hl.config({
    general = {
        border_size = 2,
        gaps_in = 2,
        gaps_out = 2,
        gaps_workspaces = 100,
        layout = "dwindle",
        resize_on_border = false,
        allow_tearing = false,
        col = {
            active_border = "rgba(" .. themes_current.color .. ")",
            inactive_border = "rgba(" .. themes_current.inactive_color .. ")",
        },
    },
})

hl.config({
    dwindle = {
        --pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- You probably want this
    },
})

hl.config({
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

hl.config({
    input = {
        kb_layout = "es",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        numlock_by_default = true,
        touchpad = {
            natural_scroll = false,
        },
    },
})
