source = /home/rodrigo/.config/hypr/themes/current.conf
source = /home/rodrigo/.config/hypr/general.conf
source = /home/rodrigo/.config/hypr/decoration.conf
source = /home/rodrigo/.config/hypr/binds.conf
source = /home/rodrigo/.config/hypr/animations.conf



monitor=,1920x1080@144,0x0,1

exec-once = waybar & swaync & hyprpaper & hyprlock & xwaylandvideobridge &
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
exec-once = hyprctl setcursor Qogir-Dark 24

env = XCURSOR_THEME, Qogir-Dark
env = XCURSOR_SIZE, 24
env = HYPRCURSOR_THEME, Qogir-Dark
env = HYPRCURSOR_SIZE, 24

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

#windowrule = suppressevent maximize, class:.*

#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
